
package com.example.soap.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LogEntryImplService", targetNamespace = "http://service.soap.example.com/", wsdlLocation = "http://localhost:8090/log?wsdl")
public class LogEntryImplService
    extends Service
{

    private final static URL LOGENTRYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGENTRYIMPLSERVICE_EXCEPTION;
    private final static QName LOGENTRYIMPLSERVICE_QNAME = new QName("http://service.soap.example.com/", "LogEntryImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/log?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGENTRYIMPLSERVICE_WSDL_LOCATION = url;
        LOGENTRYIMPLSERVICE_EXCEPTION = e;
    }

    public LogEntryImplService() {
        super(__getWsdlLocation(), LOGENTRYIMPLSERVICE_QNAME);
    }

    public LogEntryImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGENTRYIMPLSERVICE_QNAME, features);
    }

    public LogEntryImplService(URL wsdlLocation) {
        super(wsdlLocation, LOGENTRYIMPLSERVICE_QNAME);
    }

    public LogEntryImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGENTRYIMPLSERVICE_QNAME, features);
    }

    public LogEntryImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogEntryImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LogEntry
     */
    @WebEndpoint(name = "LogEntryImplPort")
    public LogEntry getLogEntryImplPort() {
        return super.getPort(new QName("http://service.soap.example.com/", "LogEntryImplPort"), LogEntry.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogEntry
     */
    @WebEndpoint(name = "LogEntryImplPort")
    public LogEntry getLogEntryImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.example.com/", "LogEntryImplPort"), LogEntry.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGENTRYIMPLSERVICE_EXCEPTION!= null) {
            throw LOGENTRYIMPLSERVICE_EXCEPTION;
        }
        return LOGENTRYIMPLSERVICE_WSDL_LOCATION;
    }

}
