
package com.example.soap.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "LogFault", targetNamespace = "http://service.soap.example.com/")
public class LogFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private LogFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public LogFault_Exception(String message, LogFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public LogFault_Exception(String message, LogFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.soap.service.LogFault
     */
    public LogFault getFaultInfo() {
        return faultInfo;
    }

}
